### PR TITLE
Make sure IP address is null-terminated before passing it to inet_pton

### LINKED ISSUE #46: [Windows] IgnoreCIDR test failure
There is an intermittent test failure, that happens in about 1 in 10 test runs and can be reproduced only on Windows:

```
======================================================================
FAIL: test_1_5 (test_34ignorecidr.ignorecidr)
TEST 1.5: Verify IgnoreCIDR x.x.x.x./32 is converted to IgnoreIP
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\naxsi\naxsi\unit-tests\python\test_34ignorecidr.py", line 196, in test_1_5
    self.assertEqual(ec, 200)
AssertionError: 412 != 200

----------------------------------------------------------------------
```

It may or may not be related to a real Windows-specific problem in IP conversion area, I intend to investigate it.

### PR DESCRIPTION
**Pull request by staticlibs**
This patch fixes #46 . The problem can be reliably reproduced without the patch (running `test_34ignorecidr.ignorecidr.test_1_5` in a loop on Windows) and cannot be reproduced with the patch. There are related questions about the `NGX_HTTP_X_FORWARDED_FOR` branch, will ask them in #46 comments.

### CODE REVIEW

**Review by wargio — APPROVED** [review]

File: naxsi_src/naxsi_runtime.c [hunk 1]
```diff
@@ -3021,14 +3021,17 @@ ngx_http_naxsi_update_current_ctx_status(ngx_http_request_ctx_t*    ctx,
 #endif
 #endif
     {
-      ngx_str_t* ip = &r->connection->addr_text;
+      ngx_str_t ip;
+      ip.len  = r->connection->addr_text.len;
+      ip.data = ngx_pcalloc(r->pool, ip.len + 1);
```
Comment (wargio) [inline naxsi_src/naxsi_runtime.c:3026]: This pointer is never freed. call ngx_pfree

Comment (staticlibs) [reply naxsi_src/naxsi_runtime.c:3036]: Added ngx_pfree.

**Review by wargio — APPROVED** [review]
